[[language]]
name = "python"
language-servers = [ "basedpyright" ]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "c"
file-types = ["c", "h"]
formatter = { command = 'clang-format' }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
